<?php
/**
 * WarehouseTransactionsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation for Sitoo
 *
 * Client for integrating to Sitoo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\SitooClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
#region SPY Code
use GuzzleHttp\Cookie\CookieJar;
#endregion
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Spy\SitooClient\ApiException;
use Spy\SitooClient\Configuration;
use Spy\SitooClient\HeaderSelector;
use Spy\SitooClient\ObjectSerializer;

/**
 * WarehouseTransactionsApi Class Doc Comment
 *
 * @category Class
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WarehouseTransactionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

	#region SPY Code
	protected $bXDebugOnInstance	= false;
	protected $bXDebugOnNextRequest;

	/**
	 * @param bool $bXDebugOnInstance
	 * @return $this
	 */
	public function setXDebugOnInstance(bool $bXDebugOnInstance)
	{
		$this->bXDebugOnInstance	= $bXDebugOnInstance;

		return $this;
	}

	/**
	 * @return $this
	 */
	public function setXDebugOnNextRequest()
	{
		$this->bXDebugOnNextRequest	= true;

		return $this;
	}

	/**
	 * Gets the OpenAPI Spec Version
	 *
	 * @return string
	 */
	public static function getSpecVersion()
	{
		return '1.0.0';
	}
	#endregion

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation batchAddWarehouseTransactions
     *
     * @param  int $siteid siteid (required)
     * @param  \Spy\SitooClient\Model\WarehousetransactionWrite[] $warehousetransactionWrite warehousetransactionWrite (required)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function batchAddWarehouseTransactions($siteid, $warehousetransactionWrite)
    {
        $this->batchAddWarehouseTransactionsWithHttpInfo($siteid, $warehousetransactionWrite);
    }

    /**
     * Operation batchAddWarehouseTransactionsWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  \Spy\SitooClient\Model\WarehousetransactionWrite[] $warehousetransactionWrite (required)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchAddWarehouseTransactionsWithHttpInfo($siteid, $warehousetransactionWrite)
    {
        $request = $this->batchAddWarehouseTransactionsRequest($siteid, $warehousetransactionWrite);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation batchAddWarehouseTransactionsAsync
     *
     * @param  int $siteid (required)
     * @param  \Spy\SitooClient\Model\WarehousetransactionWrite[] $warehousetransactionWrite (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchAddWarehouseTransactionsAsync($siteid, $warehousetransactionWrite)
    {
        return $this->batchAddWarehouseTransactionsAsyncWithHttpInfo($siteid, $warehousetransactionWrite)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchAddWarehouseTransactionsAsyncWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  \Spy\SitooClient\Model\WarehousetransactionWrite[] $warehousetransactionWrite (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchAddWarehouseTransactionsAsyncWithHttpInfo($siteid, $warehousetransactionWrite)
    {
        $returnType = '';
        $request = $this->batchAddWarehouseTransactionsRequest($siteid, $warehousetransactionWrite);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchAddWarehouseTransactions'
     *
     * @param  int $siteid (required)
     * @param  \Spy\SitooClient\Model\WarehousetransactionWrite[] $warehousetransactionWrite (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchAddWarehouseTransactionsRequest($siteid, $warehousetransactionWrite)
    {
        // verify the required parameter 'siteid' is set
        if ($siteid === null || (is_array($siteid) && count($siteid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $siteid when calling batchAddWarehouseTransactions'
            );
        }
        // verify the required parameter 'warehousetransactionWrite' is set
        if ($warehousetransactionWrite === null || (is_array($warehousetransactionWrite) && count($warehousetransactionWrite) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehousetransactionWrite when calling batchAddWarehouseTransactions'
            );
        }

        $resourcePath = '/sites/{siteid}/warehousetransactions.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($siteid !== null) {
            $resourcePath = str_replace(
                '{' . 'siteid' . '}',
                ObjectSerializer::toPathValue($siteid),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($warehousetransactionWrite)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($warehousetransactionWrite));
            } else {
                $httpBody = $warehousetransactionWrite;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );


        $operationHost = $this->config->getHost();

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllWarehouseTransactions
     *
     * @param  int $siteid siteid (required)
     * @param  int[] $warehousetransactionid warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto warehousetransactionidto (optional)
     * @param  int $datecreatedfrom datecreatedfrom (optional)
     * @param  int $datecreatedto datecreatedto (optional)
     * @param  int $warehouseid warehouseid (optional)
     * @param  int $transactiontype transactiontype (optional)
     * @param  int $start start (optional)
     * @param  int $num num (optional)
     * @param  string $sort sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse
     */
    public function getAllWarehouseTransactions($siteid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $warehouseid = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        list($response) = $this->getAllWarehouseTransactionsWithHttpInfo($siteid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $warehouseid, $transactiontype, $start, $num, $sort, $fields);
        return $response;
    }

    /**
     * Operation getAllWarehouseTransactionsWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $warehouseid (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllWarehouseTransactionsWithHttpInfo($siteid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $warehouseid = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        $request = $this->getAllWarehouseTransactionsRequest($siteid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $warehouseid, $transactiontype, $start, $num, $sort, $fields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllWarehouseTransactionsAsync
     *
     * @param  int $siteid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $warehouseid (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllWarehouseTransactionsAsync($siteid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $warehouseid = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        return $this->getAllWarehouseTransactionsAsyncWithHttpInfo($siteid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $warehouseid, $transactiontype, $start, $num, $sort, $fields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllWarehouseTransactionsAsyncWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $warehouseid (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllWarehouseTransactionsAsyncWithHttpInfo($siteid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $warehouseid = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        $returnType = '\Spy\SitooClient\Model\GetAllWarehouseTransactionsResponse';
        $request = $this->getAllWarehouseTransactionsRequest($siteid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $warehouseid, $transactiontype, $start, $num, $sort, $fields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllWarehouseTransactions'
     *
     * @param  int $siteid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $warehouseid (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllWarehouseTransactionsRequest($siteid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $warehouseid = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        // verify the required parameter 'siteid' is set
        if ($siteid === null || (is_array($siteid) && count($siteid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $siteid when calling getAllWarehouseTransactions'
            );
        }

        $resourcePath = '/sites/{siteid}/warehousetransactions.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($warehousetransactionid)) {
            $warehousetransactionid = ObjectSerializer::serializeCollection($warehousetransactionid, 'form', true);
        }
        if ($warehousetransactionid !== null) {
            $queryParams['warehousetransactionid'] = $warehousetransactionid;
        }
        // query params
        if (is_array($warehousetransactionidfrom)) {
            $warehousetransactionidfrom = ObjectSerializer::serializeCollection($warehousetransactionidfrom, '', true);
        }
        if ($warehousetransactionidfrom !== null) {
            $queryParams['warehousetransactionidfrom'] = $warehousetransactionidfrom;
        }
        // query params
        if (is_array($warehousetransactionidto)) {
            $warehousetransactionidto = ObjectSerializer::serializeCollection($warehousetransactionidto, '', true);
        }
        if ($warehousetransactionidto !== null) {
            $queryParams['warehousetransactionidto'] = $warehousetransactionidto;
        }
        // query params
        if (is_array($datecreatedfrom)) {
            $datecreatedfrom = ObjectSerializer::serializeCollection($datecreatedfrom, '', true);
        }
        if ($datecreatedfrom !== null) {
            $queryParams['datecreatedfrom'] = $datecreatedfrom;
        }
        // query params
        if (is_array($datecreatedto)) {
            $datecreatedto = ObjectSerializer::serializeCollection($datecreatedto, '', true);
        }
        if ($datecreatedto !== null) {
            $queryParams['datecreatedto'] = $datecreatedto;
        }
        // query params
        if (is_array($warehouseid)) {
            $warehouseid = ObjectSerializer::serializeCollection($warehouseid, '', true);
        }
        if ($warehouseid !== null) {
            $queryParams['warehouseid'] = $warehouseid;
        }
        // query params
        if (is_array($transactiontype)) {
            $transactiontype = ObjectSerializer::serializeCollection($transactiontype, '', true);
        }
        if ($transactiontype !== null) {
            $queryParams['transactiontype'] = $transactiontype;
        }
        // query params
        if (is_array($start)) {
            $start = ObjectSerializer::serializeCollection($start, '', true);
        }
        if ($start !== null) {
            $queryParams['start'] = $start;
        }
        // query params
        if (is_array($num)) {
            $num = ObjectSerializer::serializeCollection($num, '', true);
        }
        if ($num !== null) {
            $queryParams['num'] = $num;
        }
        // query params
        if (is_array($sort)) {
            $sort = ObjectSerializer::serializeCollection($sort, '', true);
        }
        if ($sort !== null) {
            $queryParams['sort'] = $sort;
        }
        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'form', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = $fields;
        }


        // path params
        if ($siteid !== null) {
            $resourcePath = str_replace(
                '{' . 'siteid' . '}',
                ObjectSerializer::toPathValue($siteid),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );


        $operationHost = $this->config->getHost();

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getWarehouseTransaction
     *
     * @param  int $siteid siteid (required)
     * @param  int $warehouseid warehouseid (required)
     * @param  int $warehousetransactionid warehousetransactionid (required)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\SitooClient\Model\WarehousetransactionRead
     */
    public function getWarehouseTransaction($siteid, $warehouseid, $warehousetransactionid)
    {
        list($response) = $this->getWarehouseTransactionWithHttpInfo($siteid, $warehouseid, $warehousetransactionid);
        return $response;
    }

    /**
     * Operation getWarehouseTransactionWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int $warehousetransactionid (required)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\SitooClient\Model\WarehousetransactionRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWarehouseTransactionWithHttpInfo($siteid, $warehouseid, $warehousetransactionid)
    {
        $request = $this->getWarehouseTransactionRequest($siteid, $warehouseid, $warehousetransactionid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\SitooClient\Model\WarehousetransactionRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\SitooClient\Model\WarehousetransactionRead' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\SitooClient\Model\WarehousetransactionRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\SitooClient\Model\WarehousetransactionRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\SitooClient\Model\WarehousetransactionRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getWarehouseTransactionAsync
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int $warehousetransactionid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWarehouseTransactionAsync($siteid, $warehouseid, $warehousetransactionid)
    {
        return $this->getWarehouseTransactionAsyncWithHttpInfo($siteid, $warehouseid, $warehousetransactionid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getWarehouseTransactionAsyncWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int $warehousetransactionid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWarehouseTransactionAsyncWithHttpInfo($siteid, $warehouseid, $warehousetransactionid)
    {
        $returnType = '\Spy\SitooClient\Model\WarehousetransactionRead';
        $request = $this->getWarehouseTransactionRequest($siteid, $warehouseid, $warehousetransactionid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getWarehouseTransaction'
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int $warehousetransactionid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getWarehouseTransactionRequest($siteid, $warehouseid, $warehousetransactionid)
    {
        // verify the required parameter 'siteid' is set
        if ($siteid === null || (is_array($siteid) && count($siteid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $siteid when calling getWarehouseTransaction'
            );
        }
        // verify the required parameter 'warehouseid' is set
        if ($warehouseid === null || (is_array($warehouseid) && count($warehouseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouseid when calling getWarehouseTransaction'
            );
        }
        // verify the required parameter 'warehousetransactionid' is set
        if ($warehousetransactionid === null || (is_array($warehousetransactionid) && count($warehousetransactionid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehousetransactionid when calling getWarehouseTransaction'
            );
        }

        $resourcePath = '/sites/{siteid}/warehouses/{warehouseid}/warehousetransactions/{warehousetransactionid}.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($siteid !== null) {
            $resourcePath = str_replace(
                '{' . 'siteid' . '}',
                ObjectSerializer::toPathValue($siteid),
                $resourcePath
            );
        }
        // path params
        if ($warehouseid !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseid' . '}',
                ObjectSerializer::toPathValue($warehouseid),
                $resourcePath
            );
        }
        // path params
        if ($warehousetransactionid !== null) {
            $resourcePath = str_replace(
                '{' . 'warehousetransactionid' . '}',
                ObjectSerializer::toPathValue($warehousetransactionid),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );


        $operationHost = $this->config->getHost();

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getWarehouseTransactions
     *
     * @param  int $siteid siteid (required)
     * @param  int $warehouseid warehouseid (required)
     * @param  int[] $warehousetransactionid warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto warehousetransactionidto (optional)
     * @param  int $datecreatedfrom datecreatedfrom (optional)
     * @param  int $datecreatedto datecreatedto (optional)
     * @param  int $transactiontype transactiontype (optional)
     * @param  int $start start (optional)
     * @param  int $num num (optional)
     * @param  string $sort sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\SitooClient\Model\GetWarehouseTransactionsResponse
     */
    public function getWarehouseTransactions($siteid, $warehouseid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        list($response) = $this->getWarehouseTransactionsWithHttpInfo($siteid, $warehouseid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $transactiontype, $start, $num, $sort, $fields);
        return $response;
    }

    /**
     * Operation getWarehouseTransactionsWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \Spy\SitooClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\SitooClient\Model\GetWarehouseTransactionsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWarehouseTransactionsWithHttpInfo($siteid, $warehouseid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        $request = $this->getWarehouseTransactionsRequest($siteid, $warehouseid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $transactiontype, $start, $num, $sort, $fields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\SitooClient\Model\GetWarehouseTransactionsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\SitooClient\Model\GetWarehouseTransactionsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\SitooClient\Model\GetWarehouseTransactionsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\SitooClient\Model\GetWarehouseTransactionsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\SitooClient\Model\GetWarehouseTransactionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getWarehouseTransactionsAsync
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWarehouseTransactionsAsync($siteid, $warehouseid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        return $this->getWarehouseTransactionsAsyncWithHttpInfo($siteid, $warehouseid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $transactiontype, $start, $num, $sort, $fields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getWarehouseTransactionsAsyncWithHttpInfo
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWarehouseTransactionsAsyncWithHttpInfo($siteid, $warehouseid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        $returnType = '\Spy\SitooClient\Model\GetWarehouseTransactionsResponse';
        $request = $this->getWarehouseTransactionsRequest($siteid, $warehouseid, $warehousetransactionid, $warehousetransactionidfrom, $warehousetransactionidto, $datecreatedfrom, $datecreatedto, $transactiontype, $start, $num, $sort, $fields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getWarehouseTransactions'
     *
     * @param  int $siteid (required)
     * @param  int $warehouseid (required)
     * @param  int[] $warehousetransactionid (optional)
     * @param  int $warehousetransactionidfrom (optional)
     * @param  int $warehousetransactionidto (optional)
     * @param  int $datecreatedfrom (optional)
     * @param  int $datecreatedto (optional)
     * @param  int $transactiontype (optional)
     * @param  int $start (optional)
     * @param  int $num (optional)
     * @param  string $sort (optional)
     * @param  string[] $fields list of fields, comma-separated (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getWarehouseTransactionsRequest($siteid, $warehouseid, $warehousetransactionid = null, $warehousetransactionidfrom = null, $warehousetransactionidto = null, $datecreatedfrom = null, $datecreatedto = null, $transactiontype = null, $start = null, $num = null, $sort = null, $fields = null)
    {
        // verify the required parameter 'siteid' is set
        if ($siteid === null || (is_array($siteid) && count($siteid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $siteid when calling getWarehouseTransactions'
            );
        }
        // verify the required parameter 'warehouseid' is set
        if ($warehouseid === null || (is_array($warehouseid) && count($warehouseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $warehouseid when calling getWarehouseTransactions'
            );
        }

        $resourcePath = '/sites/{siteid}/warehouses/{warehouseid}/warehousetransactions.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($warehousetransactionid)) {
            $warehousetransactionid = ObjectSerializer::serializeCollection($warehousetransactionid, 'form', true);
        }
        if ($warehousetransactionid !== null) {
            $queryParams['warehousetransactionid'] = $warehousetransactionid;
        }
        // query params
        if (is_array($warehousetransactionidfrom)) {
            $warehousetransactionidfrom = ObjectSerializer::serializeCollection($warehousetransactionidfrom, '', true);
        }
        if ($warehousetransactionidfrom !== null) {
            $queryParams['warehousetransactionidfrom'] = $warehousetransactionidfrom;
        }
        // query params
        if (is_array($warehousetransactionidto)) {
            $warehousetransactionidto = ObjectSerializer::serializeCollection($warehousetransactionidto, '', true);
        }
        if ($warehousetransactionidto !== null) {
            $queryParams['warehousetransactionidto'] = $warehousetransactionidto;
        }
        // query params
        if (is_array($datecreatedfrom)) {
            $datecreatedfrom = ObjectSerializer::serializeCollection($datecreatedfrom, '', true);
        }
        if ($datecreatedfrom !== null) {
            $queryParams['datecreatedfrom'] = $datecreatedfrom;
        }
        // query params
        if (is_array($datecreatedto)) {
            $datecreatedto = ObjectSerializer::serializeCollection($datecreatedto, '', true);
        }
        if ($datecreatedto !== null) {
            $queryParams['datecreatedto'] = $datecreatedto;
        }
        // query params
        if (is_array($transactiontype)) {
            $transactiontype = ObjectSerializer::serializeCollection($transactiontype, '', true);
        }
        if ($transactiontype !== null) {
            $queryParams['transactiontype'] = $transactiontype;
        }
        // query params
        if (is_array($start)) {
            $start = ObjectSerializer::serializeCollection($start, '', true);
        }
        if ($start !== null) {
            $queryParams['start'] = $start;
        }
        // query params
        if (is_array($num)) {
            $num = ObjectSerializer::serializeCollection($num, '', true);
        }
        if ($num !== null) {
            $queryParams['num'] = $num;
        }
        // query params
        if (is_array($sort)) {
            $sort = ObjectSerializer::serializeCollection($sort, '', true);
        }
        if ($sort !== null) {
            $queryParams['sort'] = $sort;
        }
        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'form', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = $fields;
        }


        // path params
        if ($siteid !== null) {
            $resourcePath = str_replace(
                '{' . 'siteid' . '}',
                ObjectSerializer::toPathValue($siteid),
                $resourcePath
            );
        }
        // path params
        if ($warehouseid !== null) {
            $resourcePath = str_replace(
                '{' . 'warehouseid' . '}',
                ObjectSerializer::toPathValue($warehouseid),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );


        $operationHost = $this->config->getHost();

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

		#region SPY Code
		$options[RequestOptions::HEADERS]	= [
			'X-OpenAPISpecVersion'	=> '1.0.0',
		];
		$bEnableXDebug	= $this->bXDebugOnNextRequest;

		if($bEnableXDebug === null)
		{
			$bEnableXDebug	= $this->bXDebugOnInstance;
		}

		$this->bXDebugOnNextRequest	= null;

		if($bEnableXDebug)
		{
			if(preg_match('/^(?:https?:\/\/)?([^\/:]+\.[^\/:]+)/i', $this->getConfig()->getHost(), $arrMatches) === 1)
			{
				$options['cookies'] = CookieJar::fromArray(
					[
						'XDEBUG_SESSION'	=> 'PHPSTORM',
					],
					$arrMatches[1]
				);
			}
		}
		#endregion

        return $options;
    }
}
