<?php
/**
 * InfluencercodeReadModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation for Sitoo
 *
 * Client for integrating to Sitoo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\SitooClient\Model;

/**
 * InfluencercodeReadModelFields Class Doc Comment
 *
 * @category Class
 * @description The object for influencer codes in Sitoo
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InfluencercodeReadModelFields
{
    public string $strCode = 'code';
    public string $strName = 'name';
    public string $strActive = 'active';
    public string $strDatestart = 'datestart';
    public string $strDateend = 'dateend';
    public string $strVoucherpassword = 'voucherpassword';
    public string $strVouchercode = 'vouchercode';
    public string $strVouchername = 'vouchername';
    public string $strVouchercomment = 'vouchercomment';
    public string $strMaxuses = 'maxuses';
    public string $strNumused = 'numused';
    public string $strDatelastused = 'datelastused';
    public string $strMoneyordertotal = 'moneyordertotal';
    public string $strMoneyinfluencertotal = 'moneyinfluencertotal';
    public string $strMoneyinfluencerdiscount = 'moneyinfluencerdiscount';
}

