<?php
/**
 * InfluencervouchertransactionWriteModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation for Sitoo
 *
 * Client for integrating to Sitoo
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\SitooClient\Model;

/**
 * InfluencervouchertransactionWriteModelAttributes Class Doc Comment
 *
 * @category Class
 * @description The influencer voucher transaction object.
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InfluencervouchertransactionWriteModelAttributes
{
    public string $strMoneyordertotal = 'moneyordertotal';
    public string $strMoneyinfluencertotal = 'moneyinfluencertotal';
    public string $strMoneyinfluencerdiscount = 'moneyinfluencerdiscount';
    public string $strCurrencycode = 'currencycode';
    public string $strMerchantReference = 'merchantReference';
    public string $strStaffReference = 'staffReference';
}

