<?php
/**
 * ProductgroupWriteModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation for Sitoo
 *
 * Client for integrating to Sitoo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\SitooClient\Model;

/**
 * ProductgroupWriteModelFields Class Doc Comment
 *
 * @category Class
 * @description A product group contains the VAT and type for a product.
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductgroupWriteModelFields
{
    public string $strValue = 'value';
    public string $strProductgrouptype = 'productgrouptype';
    public string $strProductgroupname = 'productgroupname';
    public string $strComment = 'comment';
}

