<?php
/**
 * ResourceReadModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation for Sitoo
 *
 * Client for integrating to Sitoo
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\SitooClient\Model;

/**
 * ResourceReadModelFields Class Doc Comment
 *
 * @category Class
 * @description A resource is an uploaded file.
 * @package  Spy\SitooClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResourceReadModelFields
{
    public string $strResourceid = 'resourceid';
    public string $strMimetype = 'mimetype';
    public string $strWidth = 'width';
    public string $strHeight = 'height';
    public string $strFilesize = 'filesize';
    public string $strDatecreated = 'datecreated';
}

