parameters:
  - name: keys
    in: query
    schema:
      type: string
  - name: date
    in: query
    schema:
      type: string
  - name: num_days
    in: query
    schema:
      type: integer
  - name: store_id
    in: query
    schema:
      type: string
get:
  operationId: getCustomMetricValues
  description: Get list of Custom Metric Values. All metrics that match the filter will be returned. Note that query parameters for date and store only filter values that are grouped on them. E.g. a metric grouped on store_id will be returned if the query param for store_id matches (regardless if query parameter for date is passed or not)
  externalDocs:
    url: https://developer.sitoo.com/api-reference/dashboard-custom-metrics#get-custom-metric-values
  tags:
    - CustomMetricsAPI
  parameters:
    - name: keys
      in: query
      schema:
        type: string
    - name: date
      in: query
      schema:
        type: string
    - name: num_days
      in: query
      schema:
        type: integer
    - name: store_id
      in: query
      schema:
        type: string
  responses:
    200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/CustomMetricValue-read.yaml'
          example: [{"key":"cm_revenue_total_budget","date":"2020-12-11","store_id":"12345","value_scalar":10000},{"key":"cm_revenue_total_budget","date":"2020-12-12","store_id":"12345","value_scalar":15000},{"key":"cm_revenue_total_budget","date":"2020-12-13","store_id":"12345","value_scalar":11000},{"key":"cm_revenue_total_budget","date":"2020-12-14","store_id":"12345","value_scalar":7000},{"key":"cm_revenue_total_budget","date":"2020-12-15","store_id":"12345","value_scalar":10000}]
    400:
      description: Invalid request
    401:
      description: Unauthorized
put:
  operationId: updateCustomMetricValues
  description: Set values for Custom Metrics
  externalDocs:
    url: https://developer.sitoo.com/api-reference/dashboard-custom-metrics#update-custom-metric-values
  tags:
    - CustomMetricsAPI
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: ../schemas/CustomMetricValue-write.yaml
        example: [{"key":"cm_revenue_total_budget","date":"2020-12-11","store_id":"12345","value_scalar":10000},{"key":"cm_revenue_total_budget","date":"2020-12-12","store_id":"12345","value_scalar":15000},{"key":"cm_revenue_total_budget","date":"2020-12-13","store_id":"12345","value_scalar":11000},{"key":"cm_revenue_total_budget","date":"2020-12-14","store_id":"12345","value_scalar":7000},{"key":"cm_revenue_total_budget","date":"2020-12-15","store_id":"12345","value_scalar":10000}]
  responses:
    200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/CustomMetricValue-read.yaml'
          example: [{"key":"cm_revenue_total_budget","date":"2020-12-11","store_id":"12345","value_scalar":10000},{"key":"cm_revenue_total_budget","date":"2020-12-12","store_id":"12345","value_scalar":15000},{"key":"cm_revenue_total_budget","date":"2020-12-13","store_id":"12345","value_scalar":11000},{"key":"cm_revenue_total_budget","date":"2020-12-14","store_id":"12345","value_scalar":7000},{"key":"cm_revenue_total_budget","date":"2020-12-15","store_id":"12345","value_scalar":10000}]
    400:
      description: Invalid request
    401:
      description: Unauthorized
    500:
      description: One or more of the requested items could not be inserted