type: object
description: Product variants collection.
required:
  - groups
  - variants
properties:
  groups:
    type: array
    items:
      $ref: 'productvariantgroup-write.yaml'
    description: Array of productvariantgroup.
  variants:
    type: array
    items:
      $ref: 'productvariant-write.yaml'
    description: Array of productvariant.