# https://openapi-generator.tech/docs/usage/#generate
apiPackage: Api
artifactVersion: 1.0.3
gitRepoId: sitoo-client
gitUserId: spysystem
invokerPackage: Spy\SitooClient
modelPackage: Model
variableNamingConvention: camelCase
