# https://openapi-generator.tech/docs/usage/#generate
apiPackage: Api
gitRepoId: sitoo-client
gitUserId: spysystem
invokerPackage: Spy\SitooClient
modelPackage: Model
variableNamingConvention: camelCase
composerVendorName: spysystem
composerProjectName: sitoo-client
